name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: Build the code
      run: dotnet build
    
    - name: npm install
      working-directory: DotnetTemplate.Web
      run: npm install
    
    - name: npm run build
      working-directory: DotnetTemplate.Web
      run: npm run build     

    - name: dotnet test
      run: dotnet test

    - name: npm t
      working-directory: DotnetTemplate.Web
      run: npm t

    - name: npm t
      working-directory: DotnetTemplate.Web
      run: npm run lint





    
    